import { MongoClient } from "mongodb";
import nodemailer from "nodemailer";

let cachedClient = null;

async function getMongoClient() {
  if (cachedClient) {
    return cachedClient;
  }

  const client = new MongoClient(process.env.MONGODB_URI);
  await client.connect();

  cachedClient = client;
  return client;
}

export default async function handler(req, res) {
  try {
    const client = await getMongoClient();

    const db = client.db("portfolio");
    const collection = db.collection("feedback");

    // =========================
    // GET - Load feedback
    // =========================
    if (req.method === "GET") {
      const feedback = await collection
        .find({})
        .sort({ createdAt: -1 })
        .toArray();

      const data = feedback.map((item) => ({
        id: item._id.toString(),
        author: item.name,
        role: item.role || "Visitor / Guest",
        subject: item.subject || "",
        email: item.email,
        message: item.message,
        rating: item.rating || 5,
        date: item.createdAt
          ? new Date(item.createdAt).toISOString().split("T")[0]
          : new Date().toISOString().split("T")[0],
      }));

      return res.status(200).json({
        success: true,
        data,
      });
    }

    // =========================
    // POST - Submit feedback
    // =========================
    if (req.method === "POST") {
      const {
        name,
        email,
        role,
        subject,
        rating,
        message,
      } = req.body || {};

      if (!name || !email || !message) {
        return res.status(400).json({
          success: false,
          error: "Name, email and message are required.",
        });
      }

      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

      if (!emailRegex.test(email)) {
        return res.status(400).json({
          success: false,
          error: "Invalid email address.",
        });
      }

      const cleanName = name.trim();
      const cleanEmail = email.trim().toLowerCase();
      const cleanRole = role?.trim() || "Visitor / Guest";
      const cleanSubject =
        subject?.trim() || "Project Inquiry / Feedback";
      const cleanMessage = message.trim();
      const cleanRating = Number(rating) || 5;

      // Save feedback to MongoDB
      const result = await collection.insertOne({
        name: cleanName,
        email: cleanEmail,
        role: cleanRole,
        subject: cleanSubject,
        rating: cleanRating,
        message: cleanMessage,
        createdAt: new Date(),
      });

      const feedbackId = result.insertedId.toString();

      // =========================
      // SMTP
      // =========================
      let emailDispatched = false;
      let emailNotice =
        "Feedback saved, but email notification could not be sent.";

      try {
        const transporter = nodemailer.createTransport({
          host: process.env.SMTP_HOST,
          port: Number(process.env.SMTP_PORT),
          secure: Number(process.env.SMTP_PORT) === 465,
          auth: {
            user: process.env.SMTP_USER,
            pass: process.env.SMTP_PASS,
          },
        });

        await transporter.sendMail({
          from: process.env.SMTP_FROM,
          to: process.env.SMTP_USER,
          replyTo: cleanEmail,

          subject: `New Portfolio Feedback - ${cleanName}`,

          text: `New feedback received through your portfolio.

Name: ${cleanName}
Email: ${cleanEmail}
Role / Organization: ${cleanRole}
Subject: ${cleanSubject}
Rating: ${cleanRating}/5

Message:
${cleanMessage}
`,

          html: `
            <div style="font-family: Arial, sans-serif; line-height: 1.6; max-width: 650px;">
              <h2>New Portfolio Feedback</h2>

              <p>You received a new feedback submission.</p>

              <hr />

              <p>
                <strong>Name:</strong> ${cleanName}
              </p>

              <p>
                <strong>Email:</strong>
                <a href="mailto:${cleanEmail}">${cleanEmail}</a>
              </p>

              <p>
                <strong>Role / Organization:</strong> ${cleanRole}
              </p>

              <p>
                <strong>Subject:</strong> ${cleanSubject}
              </p>

              <p>
                <strong>Rating:</strong> ${cleanRating}/5
              </p>

              <p><strong>Message:</strong></p>

              <div style="
                background: #f4f4f4;
                padding: 16px;
                border-radius: 8px;
                white-space: pre-wrap;
              ">
                ${cleanMessage}
              </div>

              <hr />

              <p style="font-size: 12px; color: #777;">
                This notification was generated by your portfolio feedback system.
              </p>
            </div>
          `,
        });

        emailDispatched = true;
        emailNotice = "Feedback notification dispatched to your inbox.";
      } catch (emailError) {
        console.error("Feedback email error:", emailError);
      }

      // Object expected by ContactSection.tsx
      const data = {
        id: feedbackId,
        author: cleanName,
        role: cleanRole,
        subject: cleanSubject,
        email: cleanEmail,
        message: cleanMessage,
        rating: cleanRating,
        date: new Date().toISOString().split("T")[0],
      };

      return res.status(200).json({
        success: true,
        dbSaved: true,
        emailDispatched,
        emailNotice,
        data,
      });
    }

    // Other methods
    return res.status(405).json({
      success: false,
      error: "Method not allowed",
    });
  } catch (error) {
    console.error("Feedback API error:", error);

    return res.status(500).json({
      success: false,
      error: "Unable to process feedback.",
    });
  }
}